sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # GH_TOKEN 在 [travis](https://travis-ci.org/account/repositories) 上配置, 见下一节
  keep-history: true
  on:
    branch: master
  local-dir: public
